# Generated by Django 3.2.6 on 2021-08-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name_plural': 'Photo Galleries'},
        ),
    ]
